### ISSUE TITLE
Style issues

### ISSUE THREAD

**Issue by sudeesh654** [AhamedBilal/ngx-photo-editor#7] opened 2021-03-01 09:54 UTC
Style issues showing when use cropper
![img](https://user-images.githubusercontent.com/79838730/109480908-23de6480-7aa2-11eb-886b-0a010b13902f.png)

**Comment by shalvy** [comment] 2021-04-16 13:31
ng-photo-editor, disturbes my icons
![Icons ](https://user-images.githubusercontent.com/26919655/115031735-caeb5400-9ec8-11eb-81a4-18f46effcb75.png)

**Comment by AhamedBilal** [comment] 2021-04-16 13:42
I'll fix it ASAP. I think the problem is fontawesome.

**Comment by shalvy** [comment] 2021-04-19 12:00
Thanks please do

**Comment by AhamedBilal** [comment] 2021-04-21 16:21
Issue Fixed Install the new version.

**Closed** 2021-04-21 16:21 UTC

**Comment by AhamedBilal** [comment] 2021-04-23 12:48
What's your bootstrap version?

**Comment by sudeesh654** [comment] 2021-04-27 04:12
^4.5.2

**Comment by shalvy** [comment] 2022-02-04 14:13
all of a sudden I can't edit the picture, after adding file the window to
edit is no longer appearing, tries reinstalling the ngx-photo-editor
  , tried reinstalling the modules but it did not resolve the issue

**Comment by shalvy** [comment] 2022-03-16 08:37
Hi AhamedBilal/ngx-photo-editor same issues reappeared again
